# Generated by Django 3.0.6 on 2020-07-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstocks',
            name='psShipped',
        ),
        migrations.RemoveField(
            model_name='productstocks',
            name='psShippedDate',
        ),
    ]
