# Generated by Django 3.0.6 on 2020-06-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstocks',
            name='psChecked',
            field=models.BooleanField(blank=True, default=False, help_text='是否檢驗', null=True),
        ),
        migrations.AlterField(
            model_name='productstocks',
            name='psCheckedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check_Time:'),
        ),
    ]
