# Generated by Django 3.0.6 on 2020-06-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20200608_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocks',
            name='stockNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
