# Generated by Django 3.0.6 on 2020-07-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20200713_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocks',
            name='psShipped',
            field=models.BooleanField(blank=True, default=False, help_text='是否出貨', null=True),
        ),
        migrations.AddField(
            model_name='productstocks',
            name='psShippedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check_Time:'),
        ),
    ]
