# Generated by Django 3.0.6 on 2020-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productstocks_stocknumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocks',
            name='barCodeImg',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='productstocks',
            name='stockNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
