# Generated by Django 3.0.6 on 2020-07-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20200713_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attID',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
