# Generated by Django 3.0.6 on 2020-07-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20200713_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstocks',
            name='stockNumber',
            field=models.BigIntegerField(unique=True),
        ),
    ]
