# Generated by Django 3.0.6 on 2020-06-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20200615_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstocks',
            name='barCodeImg',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
