# Generated by Django 3.0.6 on 2020-07-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20200714_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstocks',
            name='psNumbers',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productstocks',
            name='stockNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
