# Generated by Django 3.0.6 on 2020-06-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20200615_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstocks',
            name='barCodeImg',
        ),
    ]
