# Generated by Django 3.0.6 on 2020-07-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20200714_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocks',
            name='barCodeImg',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
