# Generated by Django 3.0.6 on 2020-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_productstocks_barcodeimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstocks',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create_Time:'),
        ),
    ]
