# Generated by Django 3.0.6 on 2020-07-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_productstocks_barcodeimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocks',
            name='batCodeSvg',
            field=models.TextField(null=True),
        ),
    ]
